name: image_gallery_saver
description: Local plugin to save image to gallery
version: 2.0.3
flutter:
  plugin:
    platforms:
      android:
        package: com.example.image_gallery_saver
        pluginClass: ImageGallerySaverPlugin
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter